# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20161018_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videoId',
            new_name='youtube_Id',
        ),
    ]
