# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20161018_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='youtube_Id',
            new_name='youtube_id',
        ),
    ]
