# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161024_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
